name: Download, maybe convert and publish
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write

jobs:
  download-convert-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep cron active
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
      - name: Download
        run: npm run download
      - name: Maybe convert, push, and publish
        run: |
          git config user.name ci
          git config user.email ci@nerd.bible
          git add .
          if git diff-index --cached --quiet HEAD ; then
            echo "No changes"
          else
            # npm run convert
            git add .
            git commit -m "automatic update"
            bun pm version patch
            git push origin master
            bun publish --access public
          fi
